------------------------------------------------------------------------------------------------------------------------
-- Wilson / GENERIC character examines (Chinese)

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MS_COPPER_INGOT = {
	GENERIC = "铜。",
	WARM = "还能继续锻打。",
	HOT = "软得恰到好处！不愧是我的手艺。",
	MELT = "软得像黄油！",
}
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MS_ANVIL = "科学家的本能要求精准的工具。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MS_ANVIL_HELPER = "科学家的本能要求精准的工具。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MS_FURNACE = "别把头伸进去。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MS_FURNACE_BELLOW = "我的风扇设计肯定更棒。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MS_APPLE_TREE = {
	GENERIC = "一棵普通的苹果树。",
	BURNT = "烧焦了。",
	CHOPPED = "只剩树桩了。",
}
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MS_APPLE_TREE_SNOW = STRINGS.CHARACTERS.GENERIC.DESCRIBE.MS_APPLE_TREE
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MS_APPLE = "一个新鲜的山地苹果。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MS_APPLE_COOKED = "又暖又甜。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MS_BIG_APPLE = "好大一个苹果！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MS_APPLE_CORE = "可以种下去。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MS_APPLE_PIE = "像样的山地甜点。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MS_APPLE_CARAMEL = "又黏又甜。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MS_POISONED_APPLE = "最好别吃。"
